import type { ResearchSummary, LessonBriefInput } from '../types';
import type { ResearchProvider } from './base';

const MOCK_FINDINGS: Record<string, ResearchSummary['findings']> = {
  default: [
    {
      title: 'Practical AI-assisted development patterns',
      url: 'https://example.com/ai-dev-patterns',
      excerpt:
        'Modern AI coding workflows benefit from structured prompts, clear context boundaries, and reusable instruction sets that agents can rely on across sessions.',
      relevanceNote: 'Relevant for understanding foundational AI-native development approaches',
    },
    {
      title: 'Context engineering for reliable agent behavior',
      url: 'https://example.com/context-engineering',
      excerpt:
        'Context engineering is the practice of structuring information so AI agents can reason reliably without drift, repetition, or ambiguity.',
      relevanceNote: 'Core concept for the agentic building domain',
    },
    {
      title: 'Vibecoding workflows for solo builders',
      url: 'https://example.com/vibecoding',
      excerpt:
        'Vibecoding is rapid, AI-augmented product building. The most effective vibe coders use minimal, specific prompts, checkpointed context files, and skill libraries.',
      relevanceNote: 'Practical for beginners to intermediate builders using AI tools daily',
    },
  ],
};

export class MockResearchProvider implements ResearchProvider {
  readonly name = 'mock';

  async research(brief: LessonBriefInput): Promise<ResearchSummary> {
    const findings = MOCK_FINDINGS['default'];

    return {
      query: brief.topic,
      findings,
      synthesized: `Mock research summary for "${brief.topic}": Covers foundational patterns in AI-native development, context engineering, and practical vibecoding workflows. This summary is generated by a mock provider and should be replaced with a real research adapter (Tavily, Exa, or Brave) before production use.`,
      cautionFlags: [
        'This is mock data — do not publish without real research',
        'URLs and excerpts are illustrative only',
      ],
      generatedAt: new Date().toISOString(),
      provider: 'mock',
    };
  }
}
