// lib/canon/icons.ts
//
// Canon icon systems, ported from DesignOS design-os/libraries/icons/icon-library.yaml.
// The 12 canonical semantics and the 6 approved sets. In DesignOS each set carried
// provider-native component names; here every set renders through @iconify/react, so
// each semanticMap holds the Iconify icon name (without prefix) for that collection.

import type { IconSet, IconSpecimen } from './types';

export const CANONICAL_SEMANTICS: IconSpecimen[] = [
  { id: 'search', label: 'Search' },
  { id: 'mail', label: 'Mail' },
  { id: 'phone', label: 'Phone' },
  { id: 'shield', label: 'Shield' },
  { id: 'check', label: 'Check' },
  { id: 'arrow-up-right', label: 'Arrow Up Right' },
  { id: 'globe', label: 'Globe' },
  { id: 'settings', label: 'Settings' },
  { id: 'folder', label: 'Folder' },
  { id: 'database', label: 'Database' },
  { id: 'compass', label: 'Compass' },
  { id: 'activity', label: 'Activity' },
];

export const CANON_ICON_SETS: IconSet[] = [
  {
    id: 'iconset.tabler.core',
    name: 'Tabler Icons',
    providerId: 'tabler',
    provider: 'Tabler',
    website: 'https://tabler.io/icons',
    summary: 'Crisp open-source outline icons with strong editorial clarity and dependable breadth.',
    license: 'MIT',
    source: 'canon',
    iconifyPrefix: 'tabler',
    tags: ['outline', 'editorial', 'product-ui', 'open-source'],
    supports: { outline: true, filled: true, duotone: false, animated: false },
    animation: { supported: false, notes: 'Best used as a deterministic static system for generated interfaces.' },
    preview: { strokeWidth: 1.8, cornerStyle: 'rounded', accent: '#5C6B73', surface: '#F5F2EA' },
    semanticMap: {
      search: 'search',
      mail: 'mail',
      phone: 'phone',
      shield: 'shield-check',
      check: 'check',
      'arrow-up-right': 'arrow-up-right',
      globe: 'world',
      settings: 'settings',
      folder: 'folder',
      database: 'database',
      compass: 'compass',
      activity: 'activity',
    },
  },
  {
    id: 'iconset.phosphor.duotone',
    name: 'Phosphor Icons',
    providerId: 'phosphor',
    provider: 'Phosphor',
    website: 'https://phosphoricons.com',
    summary: 'Broad icon family with duotone and weight variety, ideal for richer brand-led systems.',
    license: 'MIT',
    source: 'canon',
    iconifyPrefix: 'ph',
    tags: ['duotone', 'weights', 'expressive', 'open-source'],
    supports: { outline: true, filled: true, duotone: true, animated: false },
    animation: { supported: false, notes: 'Strong candidate when we want more visual character without vendor lock-in.' },
    preview: { strokeWidth: 1.7, cornerStyle: 'rounded', accent: '#A55D32', surface: '#F6EFE7' },
    semanticMap: {
      search: 'magnifying-glass',
      mail: 'envelope-simple',
      phone: 'phone',
      shield: 'shield-check',
      check: 'check',
      'arrow-up-right': 'arrow-up-right',
      globe: 'globe-hemisphere-west',
      settings: 'gear',
      folder: 'folder',
      database: 'database',
      compass: 'compass',
      activity: 'pulse',
    },
  },
  {
    id: 'iconset.iconoir.editorial',
    name: 'Iconoir',
    providerId: 'iconoir',
    provider: 'Iconoir',
    website: 'https://iconoir.com',
    summary: 'Lightweight editorial line icons that feel calm, premium, and slightly fashion-led.',
    license: 'MIT',
    source: 'canon',
    iconifyPrefix: 'iconoir',
    tags: ['minimal', 'editorial', 'outline', 'open-source'],
    supports: { outline: true, filled: false, duotone: false, animated: false },
    animation: { supported: false, notes: 'Great fit for restrained premium directions and typography-led sites.' },
    preview: { strokeWidth: 1.45, cornerStyle: 'sharp', accent: '#2B4A56', surface: '#EEF1ED' },
    semanticMap: {
      search: 'search',
      mail: 'mail',
      phone: 'phone',
      shield: 'shield-check',
      check: 'check',
      'arrow-up-right': 'arrow-up-right',
      globe: 'globe',
      settings: 'settings',
      folder: 'folder',
      database: 'database',
      compass: 'compass',
      activity: 'activity',
    },
  },
  {
    id: 'iconset.remix.review',
    name: 'Remix Icon',
    providerId: 'remix',
    provider: 'Remix',
    website: 'https://remixicon.com',
    summary: 'Large system with practical UI breadth and a versatile filled + outline range.',
    license: 'Remix Icon License v1.0',
    source: 'canon',
    iconifyPrefix: 'ri',
    tags: ['broad', 'ui-system', 'versatile'],
    supports: { outline: true, filled: true, duotone: false, animated: false },
    animation: { supported: false },
    preview: { strokeWidth: 1.65, cornerStyle: 'rounded', accent: '#725A39', surface: '#F4EFE7' },
    semanticMap: {
      search: 'search-line',
      mail: 'mail-line',
      phone: 'phone-line',
      shield: 'shield-check-line',
      check: 'check-line',
      'arrow-up-right': 'arrow-right-up-line',
      globe: 'globe-line',
      settings: 'settings-line',
      folder: 'folder-line',
      database: 'database-2-line',
      compass: 'compass-discover-line',
      activity: 'pulse-line',
    },
  },
  {
    id: 'iconset.lucide.motion',
    name: 'Lucide',
    providerId: 'lucide',
    provider: 'Lucide',
    website: 'https://lucide.dev',
    summary: 'Community-favourite Lucide outline system — clean, motion-friendly, ubiquitous in product UI.',
    license: 'ISC',
    source: 'canon',
    iconifyPrefix: 'lucide',
    tags: ['outline', 'motion-friendly', 'product-ui', 'open-source'],
    supports: { outline: true, filled: false, duotone: false, animated: true },
    animation: { supported: true, notes: 'Best for dashboard and studio surfaces where we want interaction-driven motion cues.' },
    preview: { strokeWidth: 1.9, cornerStyle: 'rounded', accent: '#56642B', surface: '#EEF2E6' },
    semanticMap: {
      search: 'search',
      mail: 'mail',
      phone: 'phone',
      shield: 'shield-check',
      check: 'check',
      'arrow-up-right': 'arrow-up-right',
      globe: 'globe',
      settings: 'settings',
      folder: 'folder',
      database: 'database',
      compass: 'compass',
      activity: 'activity',
    },
  },
  {
    id: 'iconset.solar.bold',
    name: 'Solar',
    providerId: 'solar',
    provider: 'Solar',
    website: 'https://www.solariconset.com',
    summary: 'Premium multi-style set with bold and duotone weights — theatrical, marketing-ready specimens.',
    license: 'CC BY 4.0',
    source: 'canon',
    iconifyPrefix: 'solar',
    tags: ['bold', 'duotone', 'marketing', 'premium'],
    supports: { outline: true, filled: true, duotone: true, animated: false },
    animation: { supported: false, notes: 'Rich weighted specimens for expressive marketing-led directions.' },
    preview: { strokeWidth: 1.2, cornerStyle: 'rounded', accent: '#9A6B38', surface: '#F8F2E8' },
    semanticMap: {
      search: 'magnifer-linear',
      mail: 'letter-linear',
      phone: 'phone-linear',
      shield: 'shield-check-linear',
      check: 'check-circle-linear',
      'arrow-up-right': 'arrow-right-up-linear',
      globe: 'global-linear',
      settings: 'settings-linear',
      folder: 'folder-linear',
      database: 'database-linear',
      compass: 'compass-linear',
      activity: 'pulse-linear',
    },
  },
];
